name: skylark
channels:
  - defaults
  - conda-forge
dependencies:
  - cvxpy
  - graphviz
  - numpy
  - pip
  - python=3.9
  - pip:
    - awscrt
    - boto3
    - cachetools
    - click
    - cvxopt
    - flask
    - google-api-python-client
    - google-cloud-compute
    - graphviz
    - loguru
    - matplotlib
    - oslo.concurrency
    - pandas
    - paramiko
    - questionary
    - ray
    - setproctitle
    - tqdm
    - typer[all]
    - werkzeug