from setuptools import setup


setup(
    name="skylark",
    version="0.1",
    packages=["skylark"],
    python_requires=">=3.8",
    install_requires=[
        "azure-mgmt-resource",
        "azure-mgmt-compute",
        "azure-mgmt-network",
        "azure-identity",
        "azure-storage-blob>=12.0.0",
        "awscrt",
        "boto3",
        "click>=7.1.2",
        "flask",
        "google-api-python-client",
        "google-cloud-compute",
        "google-cloud-storage",
        "grpcio-status>=1.33.2",
        "numpy",
        "setproctitle",
        "termcolor",
        "tqdm",
        "werkzeug",
    ],
    extras_require={
        "all": [
            "cachetools",
            "click",
            "cvxopt",
            "cvxpy",
            "graphviz",
            "matplotlib",
            "oslo.concurrency",
            "paramiko",
            "pandas",
            "questionary",
            "ray",
            "typer",
        ],
        "test": ["black", "ipython", "jupyter_console", "pytest", "pytype"],
    },
    entry_points={"console_scripts": ["skylark=skylark.cli.cli:app"]},
)
