# ray submit --start --stop data/ray_cluster_configs/config_paras_with_docker.yaml skylark/benchmark/pareto_speedups.py

# An unique identifier for the head node and workers of this cluster.
cluster_name: skylark-control-plane
upscaling_speed: 40
max_workers: 40

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    image: DOCKERIMAGEHERE
    container_name: "skylark_image"
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        # - -v /tmp/ray_tmp_mount/skylark-control-plane/tmp/.aws/credentials:/root/.aws
        # - -v /tmp/ray_tmp_mount/skylark-control-plane/tmp/config.json:/pkg/data/config.json
        - --ulimit nofile=65536:65536
        - --rm

idle_timeout_minutes: 5

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a,us-west-2b,us-west-2c
    cache_stopped_nodes: False # If not present, the default is True.

# How Ray will authenticate with newly launched nodes.
# auth:
#     ssh_user: ubuntu
#     ssh_private_key: /home/ubuntu/skylark/data/keys/aws/skylark-us-west-2.pem

available_node_types:
    # Demand information can be found at https://aws.amazon.com/ec2/spot/instance-advisor/
    # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
    ray.head.default:
        node_config:
            InstanceType: c5.24xlarge
            ImageId: ami-0a0a2849f3390a302
            # KeyName: skylark-us-west-2
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 500
                      VolumeType: gp2
                      DeleteOnTermination: true
    ray.worker.default_c5.24xlarge_spot:
        min_workers: 5
        max_workers: 40
        node_config:
            InstanceType: c5.24xlarge
            ImageId: ami-0a0a2849f3390a302
            # KeyName: skylark-us-west-2
            InstanceMarketOptions:
                MarketType: spot

head_node_type: ray.head.default

file_mounts:
    "~/.aws": "~/.aws/"
    "/pkg/data/config.json": "data/config.json"

initialization_commands:
    - pip install ray[all]
    - command -v docker >/dev/null 2>&1 || { curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && sudo usermod -aG docker $USER && sudo systemctl restart docker -f; }
    - if [ -z "$(docker ps -q)" ]; then echo "No docker containers running"; else docker kill $(docker ps -q); fi
setup_commands:
    - apt-get update && apt-get install --no-install-recommends -y openssh-client
    - pip install ray[all]
    - pip install -e '.[all]'