name: integration-test
on:
  schedule:
    - cron: '9 23 * * *'
  workflow_dispatch:
concurrency: integration-test
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        pairs:
          # AWS to AWS
          - aws:us-east-1 aws:us-east-1
          - aws:us-east-2 aws:us-west-2
          # GCP to GCP
          - gcp:us-central1-a gcp:us-central1-a
          - gcp:us-west1-a gcp:us-east1-a
          # Azure to Azure
          - azure:westus azure:westus
          - azure:eastus azure:westus
          # cross cloud tests
          - aws:us-west-1 gcp:us-west2-a
          - gcp:us-west2-a aws:us-west-1
          - aws:us-west-1 azure:westus
          - azure:westus aws:us-west-1
          - gcp:us-west2-a azure:westus
          - azure:westus gcp:us-west2-a
    timeout-minutes: 20
    env:
      STRATEGY_UUID: itest-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0b1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install Dependencies
        run: poetry install -E gateway -E solver
        if: steps.cache.outputs.cache-hit != 'true'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Skyplane init
        run: |
          poetry run skyplane config set gcp_service_account_name ${{ env.STRATEGY_UUID }}
          poetry run skyplane config set native_cmd_enabled false
          cat ~/.skyplane/config
          poetry run skyplane init -y
      - name: Test
        run: poetry run python tests/integration/cp.py ${{ matrix.pairs }}
      - name: Cleanup GCP service account
        if: always()
        run: gcloud iam service-accounts delete ${{ env.STRATEGY_UUID }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
  deprovision:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [integration]
    env:
      STRATEGY_UUID: itest-d-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0b1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('pyproject.toml') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install Dependencies
        run: poetry install -E gateway -E solver
        if: steps.cache.outputs.cache-hit != 'true'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'
      - name: Skyplane init
        run: |
          poetry run skyplane config set gcp_service_account_name ${{ env.STRATEGY_UUID }}
          poetry run skyplane init -y --disable-config-azure
      - name: Deprovision
        run: poetry run skyplane deprovision
      - name: Cleanup GCP service account
        if: always()
        run: gcloud iam service-accounts delete --quiet ${{ env.STRATEGY_UUID }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
