name: lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pytype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[gateway,solver]"
          pip install pytype
      - name: Run pytype
        run: pytype skyplane --config .pytype.cfg -j auto
  # pylint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: "3.8"
  #         cache: 'pip'
  #     - name: Cache pip dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ hashFiles('setup.py') }}-pylint-pip
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e .
  #         pip install pylint
  #     - name: Run pylint
  #       run: (find skyplane -type f -name "*.py" | xargs pylint --rcfile=.pylintrc) || true
