name: pypi

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[solver,gateway]"
          python -m pip install build
      - name: Build wheels
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Upload wheels
        run: twine upload dist/*
    - name: Publish distribution Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/