name: unittests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest
      - name: Run unit tests
        run: pytest tests/unit_nocloud

  test-aws:
    runs-on: ubuntu-latest
    depends-on: test-unit
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest
      - name: Run cloud tests
        run: |
          skyplane init -y
          pytest -s tests/unit_aws

  test-gcp:
    runs-on: ubuntu-latest
    depends-on: test-unit
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest
      - name: Run cloud tests
        run: |
          skyplane init -y
          pytest -s tests/unit_gcp

  test-azure:
    runs-on: ubuntu-latest
    depends-on: test-unit
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest
      - name: Run cloud tests
        run: |
          skyplane init -y
          pytest -s tests/unit_azure