name: unittest

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-pytest-pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U pytest
          
      - name: Run unit tests
        run: pytest skylark/test/unit_nocloud
     #- name: Run cloud tests
        ###consider only running cloud tests for PRs to main once we go open source
        ###if: ${{ github.event_name == 'pull_request' && github.base_ref == github.event.repository.default_branch }}
        #run: |
          #pytest skylark/test/unit_aws
          #pytest skylark/test/unit_azure
          #pytest skylark/test/unit_gcp
